### ISSUE TITLE
[yts] An error occurred while sending the request: Error: TrustFailure (One or more errors occurred.)

### ISSUE THREAD

**Issue by mcjfauser** [binhex/arch-jackett#1]
I'm getting an issue when trying to add **yts** indexer:
 
> An error occured while configuring this indexer
> An error occurred while sending the request: Error: TrustFailure (One or more errors occurred.)

**OS:** unRAID 6.5.0.
**Kernel:** Linux 4.14.26-unRAID x86_64
**OpenSSL:** 1.0.2n
**CPU:** Ryzen 1600

I've tried the troubleshooting step for this issue on the Jackett master README too:
 
**Output:** root@NAS:~# wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin
-bash: cert-sync: command not found
--2018-07-22 10:24:12-- https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... 151.101.82.49, 2a04:4e42:13::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.82.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 213947 (209K) [application/x-pem-file]
Saving to: ‘STDOUT’ 0%[ ] 0 --.-KB/s in 0s
Cannot write to ‘-’ (Success).

**Comment by binhex** [comment]
as this is a docker container the number of utils included is minimal to keep the size down, thus the error regards 'cert-sync: command not found'. 

im going to close this off for now, as the issue may of been fixed, and index sites break and get fixed up all the time, if its still an issue i would raise this with the jackett team as an 'issue'.
