### ISSUE TITLE
Update :d

### ISSUE THREAD

**Issue by moarf56** [binhex/arch-jackett#2]
Hi, I use your docker image and I'm asking how can I update to the last release of jackett ?
Jackett v0.10.442 is up but in the container I can't upgrade to it with the "check for update fonction" I stay on the :

`Checked for a updated release but none was found. Current: v0.10.437 Latest: v0.10.437`.

Thank you

**Comment by binhex** [comment]
you don't do in app updates you do it by stopping the container, delete the container, issue a "docker pull" to download the latest image, then re-create your container.

**Comment by moarf56** [comment]
Okay thx you :d
