### ISSUE TITLE
ICU missing on jackett latest docker

### ISSUE THREAD

**Issue by Ulisses1478** [binhex/arch-jackett#5]
OS: UNRAID
I was not able to start jackett container so i searched and i just need to run this command and was fixed 
`pacman -S icu `
My searches of the log on jackett container (not complete)
First search

> jackett entered FATAL state, too many start retries too quickly

Second search

> Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

**Comment by binhex** [comment]
This should be fixed in the latest image, please pull down and let me know if it fixes it.

**Comment by Ulisses1478** [comment]
the latest image from docker hub is 18h hours ago i'm guessing you will post an update later. So i'm closing the issue
edit: i see your code and ICU is included, I was probably not using the latest image.
