### ISSUE TITLE
Jackett needs an update

### ISSUE THREAD

**Issue by JoeMShanahan** [binhex/arch-jackett#6]
Used version of Jackett not able to talk to IPTorrents.

Suggest downgrading to 0.12.1053.0 as per https://github.com/Jackett/Jackett/issues/6446

Also, does this container use Mono or .NET Core?

**Comment by JoeMShanahan** [comment]
I've tried using the tagged template with `0.12.1053.0` suspect there's still an issue.

**Comment by binhex** [comment]
the image is bang up to date, are you using a proxy with jackett?, if so this can cause issues with certain torrent sites, as they block vpn ip ranges (assuming use of privoxy and one of my vpn enabled images).

**Comment by JoeMShanahan** [comment]
This seems to be a common problem at the moment unfortunately. I have read one solution (https://github.com/Jackett/Jackett/issues/4596) would be to configure the tracker over a VPN. Is there a relatively easy way to smash together your container and the VPN machinery you've made?
